version: '2'

services:
  db:
    image: mysql:latest # arm64v8/mysql:latest for ARM VMs
    volumes:
      - ./db_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - wp
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
       - ./wp_data:/var/www/html
    networks:
      - proxy
      - wp
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      LETSENCRYPT_HOST: dev.example.com
      VIRTUAL_HOST: dev.example.com
      VIRTUAL_PORT: 80

networks:
  wp:
  proxy:
    external: true
