---
- name: Include vars of ansible-config.yaml
  ansible.builtin.include_vars: ../../../../custom/ansible-config.yml

- name: Include secrets from Ansible Vault file (gitignored, optionally encrypted)
  ansible.builtin.include_vars: ../../../../custom/secrets/vault.yml
  ignore_errors: true

- name: Install restic
  ansible.builtin.apt:
    name: restic
    state: latest

- name: Copy backup script
  ansible.builtin.template:
    src: templates/backup.sh
    dest: /hosting/scripts/backup.sh
    mode: "0700"
    owner: root
    group: root

- name: Copy backup credentials
  ansible.builtin.copy:
    src: ../../../../custom/secrets/gcp-secret.json
    dest: /hosting/secrets/gcp-secret.json
    mode: 0600

- name: Enable daily backups at 1:00 AM
  ansible.builtin.cron:
    name: Backup containers
    minute: "0"
    hour: "1"
    job: "/hosting/scripts/backup.sh"