- hosts: all 
  vars_files:
  - ../custom/ansible-config.yml
  tasks:
  - name: Configure floating IP
    become: yes
    template:
      src: 60-floating-ip.cfg.j2
      dest: /etc/network/interfaces.d/60-floating-ip.cfg
      mode: '0644'
  - name: Restart network service
    service:
      name: networking
      state: restarted
  - name: Creating folder structure - instances
    become: yes
    file:
      path: /hosting/instances
      state: directory
      mode: 0775
      recurse: yes
  - name: Creating folder structure - scripts
    become: yes
    file:
      path: /hosting/scripts
      state: directory
      mode: 0775
      recurse: yes
  - name: Creating folder structure - secrets
    become: yes
    file:
      path: /hosting/secrets
      state: directory
      mode: 0775
      recurse: yes
  - name: Copy scripts
    copy:
      src: ../scripts/
      dest: /hosting/scripts/
      mode: 0775
  - name: Update backup script configuration
    template:
      src: ../scripts/backup.sh
      dest: /hosting/scripts/backup.sh
  - name: Install backup software
    apt:
      name: "restic"
      state: latest
    become: yes
  - name: Copy backup credentials
    copy:
      src: ../custom/secrets/gcp-secret.json
      dest: /hosting/secrets/gcp-secret.json
      mode: 0775
  - name: Create proxy docker network
    become: yes
    command: docker network create proxy
    ignore_errors: yes
  - name: Create dbadmin docker network
    become: yes
    command: docker network create dbadmin
    ignore_errors: yes
  - name: Copy basic service instance files
    copy:
      src: ../instances/
      dest: /hosting/instances/
  - name: Copy custom service instance files
    copy:
      src: ../custom/instances/
      dest: /hosting/instances/
  - name: Initializing containers
    become: yes
    command: chdir=/hosting/scripts ./update.sh
  - name: Enable auto-backups
    cron:
      name: "Backup containers every day at (1:00 AM)"
      weekday: "0"
      minute: "0"
      hour: "1"
      job: "/hosting/scripts/backup.sh"
  - name: Enable auto-updates and configuration changes on reboot
    cron:
      name: "Update containers at reboot"
      special_time: reboot
      job: "/hosting/scripts/update.sh"
  - name: Enable auto-reboot every week
    cron:
      name: "Reboot every week (Sun. 3:30 AM)"
      weekday: "0"
      minute: "30"
      hour: "3"
      job: "/sbin/shutdown -r now"
  - name: Install firewall software
    apt:
      name: "ufw"
      state: latest
  - name: Copy firewall rules
    copy:
      src: ../ansible/security/ufw-rules.conf
      dest: /hosting/secrets/ufw-rules.conf
  - name: Copy custom firewall rules
    copy:
      src: ../custom/ansible/security/custom-ufw.conf
      dest: /hosting/secrets/custom-ufw.conf
  - name: "Update firewall rules"
    command: bash /hosting/scripts/setup-ufw.sh
