- hosts: all 
  tasks:
  - name: Upgrade all apt packages
    become: yes
    apt: upgrade=dist force_apt_get=yes
  
  - name: Creating folder structure - scripts
    become: yes
    file:
      path: /hosting/scripts
      state: directory
      mode: 0775
      recurse: yes

  - name: Creating folder structure - services
    become: yes
    file:
      path: /hosting/instances
      state: directory
      mode: 0775
      recurse: yes

  - name: Creating folder structure - secrets
    become: yes
    file:
      path: /hosting/secrets
      state: directory
      mode: 0775
      recurse: yes

  - name: Copy update script
    copy:
      src: ../scripts/update.sh
      dest: /hosting/scripts/update.sh
      mode: 0775

  - name: Enable auto-updates and configuration changes on reboot
    cron:
      name: "Update containers at reboot"
      special_time: reboot
      job: "/hosting/scripts/update.sh"

  - name: Enable auto-reboot every week
    cron:
      name: "Reboot every week (Sun. 3:30 AM)"
      weekday: "0"
      minute: "30"
      hour: "3"
      job: "/sbin/shutdown -r now"