- hosts: all 
  tasks:
  - name: Install security packages
    become: yes
    apt:
      name: "{{ packagesdep }}"
      force_apt_get: yes
      state: latest
      update_cache: yes
    vars:
      packagesdep:
      - apt-transport-https
      - clamav
      - debsums
      - apt-show-versions
      - libpam-passwdqc
      - ntp
      - ufw

  - name: Copy limits.conf
    copy:
      src: ../ansible-config/05-security/limits.conf
      dest: /etc/security/limits.conf

  - name: Update sshd config
    copy:
      src: ../ansible-config/05-security/sshd_config
      dest: /etc/ssh/sshd_config

  - name: Disable not required kernel modules
    copy:
      src: ../ansible-config/05-security/security-blacklist.conf
      dest: /etc/modprobe.d/blacklist.conf
    
  - name: Copy firewall script
    copy:
      src: ../scripts/firewall.sh
      dest: /hosting/scripts/firewall.sh
      mode: 0775

  - name: Copy firewall rules
    copy:
      src: ../ansible-config/05-security/ufw-rules.conf
      dest: /hosting/secrets/ufw-rules.conf

#  - name: Copy custom firewall rules
#    copy:
#      src: ../custom/ansible/security/custom-ufw.conf
#      dest: /hosting/secrets/custom-ufw.conf

  - name: "Update firewall rules"
    command: bash /hosting/scripts/firewall.sh