---
- name: Configure hosting services
  hosts: all
  tasks:
    - name: Create proxy Docker network
      ansible.builtin.command:
        cmd: docker network create proxy
        creates: /hosting/.docker-network-proxy

    - name: Mark proxy network as created
      ansible.builtin.file:
        path: /hosting/.docker-network-proxy
        state: touch

    - name: Copy service files
      ansible.builtin.copy:
        src: ../services/
        dest: /hosting/instances/

    - name: Initialize containers
      ansible.builtin.command: /hosting/scripts/update.sh