- hosts: all 
  vars_files:
    - ../../custom/ansible-config.yml
  tasks:
  - name: Create proxy docker network
    become: yes
    command: docker network create proxy
    ignore_errors: yes

  - name: Copy service files
    copy:
      src: ../services/
      dest: /hosting/instances/
    when: skip_base_service|bool == false

  - name: Initializing containers
    become: yes
    command: /hosting/scripts/update.sh