version: '2'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data:/data
  files:
    image: filebrowser/filebrowser
    container_name: filebrowser
    ports:
      - "9001:80"
    volumes:
      - "/hosting/:/srv" 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "9002:80"
    volumes:
      - "./data:/etc/phpmyadmin/"
    networks:
      - "dbadmin"

networks:
  dbadmin:
    external: true