# Credentials for Google Cloud Storage backup (Restic)
GCP_Project_ID: ""
GCP_Bucket_Name: ""
GCP_Backup_Password: ""

# Domain used for hosting services. Required for automated SSL certificate provisioning
hosting_domain: "example.org"

# Details of the non-root user created on the server
user_name: hetzner-user
user_password: pleasechangeme