version: '2'

services:
  portainer:
    image: portainer/portainer
    container_name: 00_Management_Portainer
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data:/data"

