version: '2'

services:
  portainer:
    image: portainer/portainer
    container_name: 00_Management_Portainer
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data:/data"
    environment:
      LETSENCRYPT_HOST: docker.{{ hosting_domain }}
      VIRTUAL_HOST: docker.{{ hosting_domain }}
      VIRTUAL_PORT: 9000
    networks:
    - proxy

networks:
  proxy:
    external: true
