---
- name: Install dependencies for apt over HTTPS
  ansible.builtin.apt:
    name:
      - ca-certificates
      - gnupg
      - curl
    force_apt_get: yes
    state: latest
    update_cache: yes

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture[ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install Docker CE
  ansible.builtin.apt:
    name: docker-ce
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Install Docker Compose plugin
  ansible.builtin.apt:
    name: docker-compose-plugin
    state: latest
