---
- name: Install dependencies for apt over HTTPS
  ansible.builtin.apt:
    name:
      - ca-certificates
      - gnupg
      - curl
    force_apt_get: yes
    state: latest
    update_cache: yes

- name: Add Docker apt key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture[ansible_architecture] }}] https://download.docker.com/linux/debian bookworm stable"
    state: present

- name: Install Docker CE
  ansible.builtin.apt:
    name: docker-ce
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Install Docker Compose plugin
  ansible.builtin.apt:
    name: docker-compose-plugin
    state: latest
