---
- name: Install security packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - debsums
      - apt-show-versions
      - libpam-passwdqc
      - systemd-timesyncd
      - fail2ban
    force_apt_get: yes
    state: latest
    update_cache: yes

- name: Copy limits.conf
  ansible.builtin.copy:
    src: templates/limits.conf
    dest: /etc/security/limits.conf

- name: Update sshd config
  ansible.builtin.copy:
    src: templates/sshd_config
    dest: /etc/ssh/sshd_config
  notify: restart ssh

- name: Disable unnecessary kernel modules
  ansible.builtin.copy:
    src: templates/security-blacklist.conf
    dest: /etc/modprobe.d/disable-unused-protocols.conf

- name: Create fail2ban jail configuration
  ansible.builtin.template:
    src: templates/jail.local
    dest: /etc/fail2ban/jail.local
    mode: 0644
  notify: restart fail2ban

- name: Create nginx-proxy fail2ban filter
  ansible.builtin.copy:
    src: templates/nginx-proxy.conf
    dest: /etc/fail2ban/filter.d/nginx-proxy.conf
    mode: 0644
  notify: restart fail2ban

- name: Enable and start fail2ban
  ansible.builtin.service:
    name: fail2ban
    enabled: yes
    state: started